env: dev
client-location: "http://localhost:3000"
app-name: "adon"
app-icon-default-path: ""
app-icon-darwin-path: ""
work-space-directory: "/Users/tauhoo/Documents/adon-desktop/server/data"
base-directory-path: "/Users/tauhoo/Documents/adon-desktop/server/dependencies"
version-astilectron: "0.55.0"
version-electron: "19.0.0"
