env: dev
client-location: "http://localhost:3000"
app-name: "adon"
app-icon-default-path: ""
app-icon-darwin-path: ""
work-space-directory: "temp"
base-directory-path: "dependencies"
version-astilectron: "0.55.0"
version-electron: "19.0.0"
