env: dev
client-location: "http://localhost:3000"
app-name: "adon"
app-icon-default-path: "/Users/tauhoo/Documents/adon-desktop/server/resources/logo.png"
app-icon-darwin-path: "/Users/tauhoo/Documents/adon-desktop/server/resources/logo.icns"
work-space-directory: "/Users/tauhoo/Documents/adon-desktop/server/data"
base-directory-path: "/Users/tauhoo/Documents/adon-desktop/server/dependencies"
home-path: "/Users/tauhoo"
version-astilectron: "0.55.0"
version-electron: "19.0.0"
